### ISSUE TITLE
Instructions provided to untar ESP Monitoring are incorrect

### ISSUE THREAD

**Issue by aintbrokedontfix** [sassoftware/iot-kubernetes-monitoring-esp#2]
The Readme instructs the user to untar the ESP monitoring file as follows, which incorrect:

> ...unpack it in a folder of your choice using the following command:
> 
> `tar -xzv ESP_Monitor.tar.gz --dir=${HOME}`

The command should be (notice tar command options and file name): 
`tar -xzvf ESP_Monitoring.tar.gz --dir=${HOME}`

**Comment by myuser-git** [comment]
Fixed.
