### ISSUE TITLE
gzip: ESP_Monitoring.tar.gz: not in gzip format

### ISSUE THREAD

**Issue by aintbrokedontfix** [sassoftware/iot-kubernetes-monitoring-esp#3]
tar and gunzip complain that ESP_Monitoring.tar.gz: it's not in gzip format.

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by myuser-git** [comment]
The command to extract the binaries is the following:

tar -xzvf ESP_Monitoring.tar.gz [--dir=<optional target folder]

There is no need to untar and unzip the file using separate processes.

**Comment by myuser-git** [comment]
The command to extract the binaries is the following:

tar -xzvf ESP_Monitoring.tar.gz [--dir=<optional target folder]

There is no need to untar and unzip the file using separate processes.
